<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>.net8.0-windows7.0</TargetFrameworks>
        <RootNamespace>Forge</RootNamespace>
        <Nullable>enable</Nullable>
        <PlatformTarget>x86</PlatformTarget>
        <LangVersion>12.0</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DebugType>portable</DebugType>
        <OutputPath>$(SolutionDir)BUILD\Forge\$(Configuration)</OutputPath>
        <SignAssembly>False</SignAssembly>
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <Platforms>x86</Platforms>

        <!-- Remove warnings for native binding generations -->
        <NoWarn>CA1051,CA1707,CA1708,CA1715,CA1716,CS8618,CS0169,CA2211</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <!--NuGet Package settings:-->
        <Title>S4Forge</Title>
        <PackageId>S4Forge</PackageId>
        <Authors>WizzardMaker</Authors>
        <Description>
            S4Forge - Modding Framework for Settlers 4
        </Description>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageOutputPath>$(SolutionDir)BUILD\NuGet\</PackageOutputPath>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <FileVersion>$(AssemblyVersion)</FileVersion>
        <Version>$(AssemblyVersion)</Version>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>

        <RepositoryUrl>https://github.com/Settlers-4-Reforged/S4Forge</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="BUILD\**" />
        <EmbeddedResource Remove="BUILD\**" />
        <None Remove="BUILD\**" />

        <None Include="README.md" Pack="true" PackagePath="\" />

        <PackageReference Include="AutomaticInterface" Version="5.2.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="DryIoc" Version="5.4.3" PrivateAssets="all" />
        <PackageReference Include="S4Forge.SDK" Version="0.5.*" PrivateAssets="all" />
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.102" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <None Remove=".git" />
        <None Remove=".gitignore" />
    </ItemGroup>

    <Import Project="$(ProjectDir)ForgeBuild.props" />
</Project>
