using Forge.Native;
using Forge.Native.Helpers;

namespace Forge.Native
{
    [NativeTypeName("DWORD")]
    public enum S4Edition : uint
    {
        Gold = 1,
        History = 2,
    }

    public enum Team
    {
        Red = 0,
        Blue,
        Green,
        Yellow,
        Purple,
        Orange,
        Cyan,
        White,
        Max,
    }

    public enum Tribe
    {
        Roman = 0,
        Viking,
        Maya,
        Dark,
        Trojan,
        Default = -1,
        None = 255,
        Any = 254,
    }

    public enum PersistentRole : byte
    {
        Unknown,
        PileAnywhere,
        PileBuildingSite,
        PileDelivery,
        PileProduction,
        PileStorage,
        PileTrade,
        BuildingWorkup,
        BuildingAnimalranch,
        BuildingMilitary,
        BuildingCastle,
        BuildingTrading,
        BuildingBarrack,
        BuildingBigtemple,
        BuildingSite,
        BuildingMushroomfarm,
        BuildingDarktemple,
        BuildingEyecatcher,
        BuildingFarm,
        BuildingGather,
        BuildingLookouttower,
        BuildingManakopterhall,
        BuildingMine,
        BuildingProduction,
        BuildingResidence,
        BuildingSimple,
        BuildingSmalltemple,
        BuildingStorage,
        BuildingWorkshop,
        SettlerBuilder,
        SettlerCarrier,
        SettlerDarkgardener,
        SettlerDigger,
        SettlerDonkey,
        SettlerDoor,
        SettlerFlee,
        SettlerFreeworker,
        SettlerHouseworker,
        SettlerHunter,
        SettlerMushroomfarmer,
        SettlerSlave,
        SettlerTowersoldier,
        SettlerGardener,
        SettlerGeologist,
        SettlerPioneer,
        SettlerPriest,
        SettlerThief,
        SettlerSoldier,
        SettlerSquadleader,
        SettlerHjb,
        SettlerShaman,
        SettlerSaboteur,
    }

    public enum EntityClass : byte
    {
        Unknown,
        Building,
        Pile,
        Settler,
        Landanimal,
        Cart,
        CatapultMaya,
        CatapultTrojan,
        CatapultRoman,
        CatapultViking,
        Ferry,
        Transportship,
        WarshipMaya,
        WarshipTrojan,
        WarshipRoman,
        WarshipViking,
        Manakopter,
        Deco,
        Hive,
        Mushroom,
        Plant,
        ShadowHerb,
        Stone,
        Tree,
    }

    public enum GroundType : byte
    {
        Water1 = 0,
        Water2 = 1,
        Water3 = 2,
        Water4 = 3,
        Water5 = 4,
        Water6 = 5,
        Water7 = 6,
        Water8 = 7,
        Grass = 16,
        GrassRock = 17,
        GrassIsle = 18,
        GrassDesert = 20,
        GrassSwamp = 21,
        GrassMud = 23,
        Darkgrass = 24,
        DarkgrassGrass = 25,
        Sandyroad = 28,
        Cobbledroad = 29,
        Rock = 32,
        RockGrass = 33,
        RockSnow = 35,
        Beach = 48,
        Desert = 64,
        DesertGrass = 65,
        Swamp = 80,
        SwampGrass = 81,
        River1 = 96,
        River2 = 97,
        River3 = 98,
        River4 = 99,
        Snow = 128,
        SnowRock = 129,
        Mud = 144,
        MudGrass = 145,
    }

    public enum ResourceType : byte
    {
        None,
        Fish,
        Coal = Fish + 16,
        Iron = Coal + 16,
        Gold = Iron + 16,
        Sulfur = Gold + 16,
        DeepStone = Sulfur + 16,
        Stone = DeepStone + 16,
        Tree = Stone + 16,
    }

    public enum EntityRole : byte
    {
        Unknown,
        PileAnywhere,
        PileBuildingSite,
        PileDelivery,
        PileProduction,
        PileStorage,
        PileTrade,
        BuildingWorkup,
        BuildingAnimalranch,
        BuildingMilitary,
        BuildingCastle,
        BuildingTrading,
        BuildingBarrack,
        BuildingBigtemple,
        BuildingSite,
        BuildingMushroomfarm,
        BuildingDarktemple,
        BuildingEyecatcher,
        BuildingFarm,
        BuildingGather,
        BuildingLookouttower,
        BuildingManakopterhall,
        BuildingMine,
        BuildingProduction,
        BuildingResidence,
        BuildingSimple,
        BuildingSmalltemple,
        BuildingStorage,
        BuildingWorkshop,
        SettlerBuilder,
        SettlerCarrier,
        SettlerDarkgardener,
        SettlerDigger,
        SettlerDonkey,
        SettlerDoor,
        SettlerFlee,
        SettlerFreeworker,
        SettlerHouseworker,
        SettlerHunter,
        SettlerMushroomfarmer,
        SettlerSlave,
        SettlerTowersoldier,
        SettlerGardener,
        SettlerGeologist,
        SettlerPioneer,
        SettlerPriest,
        SettlerThief,
        SettlerSoldier,
        SettlerSquadleader,
        SettlerHjb,
        SettlerShaman,
        SettlerSaboteur,
    }

    [NativeTypeName("BOOL")]
    public enum EntityCause
    {
        Destructed = 1,
        Constructed,
    }

    [NativeTypeName("DWORD")]
    public enum MovementType : uint
    {
        Forward,
        Patrol,
        Accumulate,
        Watch = 4,
        Stop = 8,
    }

    public enum GoodType : byte
    {
        None = 0,
        Agave,
        Ammo,
        Armor,
        Axe,
        Battleaxe,
        Blowgun,
        Board,
        Bow,
        Bread,
        Coal,
        Fish,
        Flour,
        Goat,
        Goldbar,
        Goldore,
        Grain,
        Gunpowder,
        Hammer,
        Honey,
        Ironbar,
        Ironore,
        Log,
        Mead,
        Meat,
        Pickaxe,
        Pig,
        Rod,
        Saw,
        Scythe,
        Sheep,
        Shovel,
        Stone,
        Sulfur,
        Sword,
        Tequila,
        Water,
        Wine,
        Backpackcatapult,
        Goose,
        Explosivearrow,
        Sunfloweroil,
        Sunflower,
    }

    public enum BuildingType : byte
    {
        None = 0,
        Woodcutterhut,
        Foresterhut,
        Sawmill,
        Stonecutterhut,
        Waterworkhut,
        Fisherhut,
        Hunterhut,
        Slaughterhouse,
        Mill,
        Bakery,
        Grainfarm,
        Animalranch,
        Donkeyranch,
        Stonemine,
        Ironmine,
        Goldmine,
        Coalmine,
        Sulfurmine,
        Smeltgold,
        Smeltiron,
        Toolsmith,
        Weaponsmith,
        Vehiclehall,
        Barracks,
        Charcoalmaker,
        Trainingcenter,
        Healerhut,
        Ammomakerhut,
        Gunpowdermakerhut,
        Landscapemakerhut,
        Shipyard,
        Port,
        Marketplace,
        Storagearea,
        Vinyard,
        Agavefarmerhut,
        Tequilamakerhut,
        Beekeeperhut,
        Meadmakerhut,
        Residencesmall,
        Residencemedium,
        Residencebig,
        Smalltemple,
        Bigtemple,
        Lookouttower,
        Guardtowersmall,
        Guardtowerbig,
        Castle,
        Mushroomfarm,
        Darktemple,
        Fortress,
        Porta,
        Portb,
        Portc,
        Portd,
        Porte,
        Portf,
        Shipyarda,
        Shipyardb,
        Shipyardc,
        Shipyardd,
        Shipyarde,
        Shipyardf,
        Eyecatcher01,
        Eyecatcher02,
        Eyecatcher03,
        Eyecatcher04,
        Eyecatcher05,
        Eyecatcher06,
        Eyecatcher07,
        Eyecatcher08,
        Eyecatcher09,
        Eyecatcher10,
        Eyecatcher11,
        Eyecatcher12,
        Shipyardg,
        Shipyardh,
        Portg,
        Porth,
        Manacopterhall,
        Sunfloweroilmakerhut,
        Sunflowerfarmerhut,
    }

    public enum SettlerType : byte
    {
        None = 0,
        Carrier,
        Digger,
        Builder,
        Woodcutter,
        Stonecutter,
        Forester,
        Farmergrain,
        Farmeranimals,
        Fisher,
        Waterworker,
        Hunter,
        Sawmillworker,
        Smelter,
        Mineworker,
        Smith,
        Miller,
        Baker,
        Butcher,
        Shipyardworker,
        Healer,
        Charcoalmaker,
        Ammomaker,
        Vehiclemaker,
        Vintner,
        Beekeeper,
        Meadmaker,
        Agavefarmer,
        Tequilamaker,
        Swordsman01,
        DarkWarrior = Swordsman01,
        Swordsman02,
        Swordsman03,
        Bowman01,
        DarkThrower = Bowman01,
        Bowman02,
        Bowman03,
        Medic01,
        Medic02,
        Medic03,
        Axewarrior01,
        Axewarrior02,
        Axewarrior03,
        Blowgunwarrior01,
        Blowgunwarrior02,
        Blowgunwarrior03,
        Squadleader,
        Priest,
        Saboteur,
        Pioneer,
        Thief,
        Geologist,
        Gardener,
        Landscaper,
        Darkgardener,
        Mushroomfarmer,
        Shaman,
        SlavedSettler,
        TempleServant,
        Angel01,
        Angel02,
        Angel03,
        Donkey,
        Backpackcatapultist01,
        Backpackcatapultist02,
        Backpackcatapultist03,
        Sunflowerfarmer,
        Sunfloweroilmaker,
        Manacoptermaster,
        Unk68 = 68,
        Unk69 = 69,
    }

    public enum AnimalType : byte
    {
        None = 0,
        Hog = 1,
        Bug1 = 2,
        Bug2 = 3,
        DeerFemale = 4,
        DeerMale = 5,
        Fox = 6,
        Chicken = 7,
        Jaguar = 8,
        BunnyRed = 9,
        Dolphin = 10,
        SeaMonster = 11,
        Shark = 12,
        Bear = 13,
        Wolf = 14,
        Fish = 15,
        BunnyGray = 16,
        Bull = 17,
        Seagul = 0,
        Donkey = 0,
        Butterfly1 = 0,
        Butterfly2 = 0,
        Butterfly3 = 0,
        DuckMale = 0,
        DuckFemale = 0,
        Parrot = 0,
    }

    public enum VehicleType : byte
    {
        None = 0,
        Warship,
        Ferry,
        Transportship,
        Warmachine,
        Cart,
        FoundationCart,
    }

    public enum TreeType : byte
    {
        None = 0,
        Oak = 1,
        Beech = 2,
        Ash = 3,
        Linden = 4,
        Birch = 5,
        Poplar = 6,
        Chestnut = 7,
        Maple = 8,
        Fir = 9,
        Spruce = 10,
        Coconut = 11,
        Date = 12,
        Walnut = 13,
        Corkoak = 14,
        Pine = 15,
        Pine2 = 16,
        OliveLarge = 17,
        OliveSmall = 18,
        Roman1 = Fir,
        Roman2 = Spruce,
        Viking1 = Fir,
        Viking2 = Spruce,
        Maya1 = Walnut,
        Maya2 = Corkoak,
        Trojan1 = Pine,
        Trojan2 = Pine2,
        Trojan3 = OliveLarge,
        Trojan4 = OliveSmall,
    }

    public enum SoundType : byte
    {
        None = 0,
    }

    public enum SpellType : byte
    {
        SpellNone = 0,
        Spell1,
        Spell2,
        Spell3,
        Spell4,
        Spell5,
        Spell6,
        Spell7,
        Spell8,
    }
}
