using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;

namespace Forge.Game.Match.Native {
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1)]
    public unsafe struct GameState {
        void* field_0;
        fixed byte gap_4[12];
        void* senderPort;
        uint receiverPort;
        uint field_18;
        fixed byte gap_1C[12];
        int field_28;
        uint field_2C;
        int field_30;
        int field_34;
        int field_38;
        int field_3C;
        int field_40;
        int field_44;
        int field_48;
        int field_4C;
        int field_50;
        int field_54;
        int field_58;
        int field_5C;
        int field_60;
        int field_64;
        int field_68;
        uint field_6C;
        fixed byte gap_70[32];
        uint field_90;
        fixed byte gap_94[68];
        fixed uint humanPlayerIds[8];
        uint field_F8;
        uint field_FC;
        uint field_100;
        fixed byte gap_104[61];
        fixed uint field_144[9];
        fixed byte gap_148[36];
        fixed uint field_18C[9];
        uint field_1B0;
        uint* field_1B4;
        fixed byte gap_1B8[112];
        uint field_228;
        fixed uint playerIds[9];
        fixed byte gap_250[9];
        char field_259;
        fixed byte gap_25A[2];
        int field_25C;
        int field_260;
        int field_264;
        fixed byte gap_268[36];
        int networkTimeDelta;
        uint field_290;
        fixed byte gap_294[12];
        int field_2A0;
        uint field_2A4;
        int multiplayerMode;
        char field_2AC;
        byte IsAutosave;
        fixed byte gap_2AE[2];
        int field_2B0;
        uint SaveGameFile;
        fixed byte gap_2B8[12];
        int field_2C4;
        uint field_2C8;
        char field_2CC;
        fixed byte gap_2CD[3];
        int field_2D0;
        int field_2D4;
        int field_2D8;
        char field_2DC;
        fixed byte gap_2DD[3];
        int field_2E0;
        uint field_2E4;
        fixed byte gap_2E8[12];
        int field_2F4;
        uint field_2F8;
        int field_2FC;
        short field_300;
        char field_302;
        byte gap_303;
        uint field_304;
        fixed byte gap_308[12];
        int field_314;
        uint field_318;
        uint field_31C;
        fixed byte gap_320[12];
        int field_32C;
        uint field_330;
        short field_334;
        fixed byte gap_336[2];
        int maxPlayerCount;
        int field_33C;
        short field_340;
        fixed byte gap_342[2];
        int field_344;
        int field_348;
        char field_34C;
        fixed byte gap_34D[3];
        char field_350;
        fixed byte gap_351[3];
        int field_354;
        uint field_358;
        fixed byte gap_35C[12];
        int field_368;
        uint field_36C;
        uint field_370;
        fixed byte gap_374[12];
        int field_380;
        uint field_384;
        uint field_388;
        fixed byte gap_38C[12];
        int field_398;
        uint field_39C;
        uint field_3A0;
        fixed byte gap_3A4[12];
        int field_3B0;
        uint field_3B4;
        short field_3B8;
        fixed byte gap_3BA[18];
        int field_3CC;
        int field_3D0;
        int field_3D4;
        int listA;
        fixed byte gap_3DC[212];
        uint listB;
        fixed byte gap_4B4[212];
        int field_588;
        byte field_58C;
        byte playerIdNumber;
        ushort field_58E;
        int field_590;
        int field_594;
        short field_598;
        fixed byte gap_59A[2];
        int field_59C;
        int field_5A0;
        int field_5A4;
        int field_5A8;
    };

}
